apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nexus.cred }}
  namespace: {{ .Values.global.namespace }}
data:
  .dockerconfigjson: >-
    {{ .Values.nexus.dockerjson }}
type: kubernetes.io/dockerconfigjson
